%YAML:1.0

dataset_dir: ./data/dataset/sequences/05

num_features: 150
num_features_init: 50
num_features_tracking: 50
num_features_tracking_bad: 20
num_features_needed_for_keyframe: 80

num_active_keyframes: 17

left_cam_index: 0
right_cam_index: 1
is_color_input: 0